name: checkmate
description: A new Flutter project for CheckMate task management app.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjusted to a common modern Dart SDK range

dependencies:
  flutter:
    sdk: flutter

  # Add common packages that will likely be needed:
  intl: ^0.18.0 # For date/time formatting
  google_fonts: ^6.1.0 # For custom fonts, matching Inter from web
  flutter_svg: ^2.0.7 # If any SVGs are used (like the favicon example)
  material_design_icons_flutter: ^7.0.7296 # For Material Icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An example of adding fonts from package dependencies:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
